# Generated by Django 3.0.7 on 2020-06-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koz', '0003_auto_20200617_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tchater',
        ),
    ]
