# Generated by Django 2.2.8 on 2020-06-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz', '0006_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tchater',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salonTchat', to='koz.Salon'),
            preserve_default=False,
        ),
    ]
