# Generated by Django 2.2.8 on 2020-06-19 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koz', '0007_tchater_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tchater',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTchat', to=settings.AUTH_USER_MODEL),
        ),
    ]
