# Generated by Django 2.2.8 on 2020-06-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koz', '0008_auto_20200619_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tchater',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
